### ISSUE TITLE
Missing timescale_analytics_experimental schema

### ISSUE THREAD

**Issue by usego** [timescale/timescale-analytics#91]
It seems I'm missing something very obvious, but I do not see timescale_analytics_experimental schema in newly created timescaledev/timescale-analytics:nightly docker

`
SELECT * FROM pg_extension

13441	plpgsql	10	11	false	1.0	NULL	NULL
16384	timescaledb	10	2200	false	2.1.0	{16399,16401,16422,16436,16451,16449,16470,16468,16486,16484,16507,16523,16525,16541,16553,16555,16598,16606,16627,16637,16641,16658,16677,16692,16829,16835,16832}	{,,,,,,,,,,,,,,,WHERE id >= 1000,
  WHERE KEY = 'exported_uuid' ,,,,,,,,,,}
`

`
CREATE EXTENSION IF NOT EXISTS timescale_analytics;
SQL Error [58P01]: ERROR: could not open extension control file "/usr/local/share/postgresql/extension/timescale_analytics.control": No such file or directory
`

Should I somehow enable it?

**Comment by usego** [comment]
Seems to be connected with this [PR](https://github.com/timescale/timescale-analytics/pull/90/commits/fdbd507625c78a38d75aa1ea14cfe162fc3fc063)

**Comment by usego** [comment]
PR fixed an issue, thanks

**Comment by davidkohn88** [comment]
Thanks for the bug report @usego ! Glad we fixed it quickly there. 

Mind me asking what features you're looking to try out?
